table Geography
	lineageTag: 584ba023-9d19-41fb-8e50-e85c41ead657

	column Country
		dataType: string
		lineageTag: baa77eb0-788f-4f39-99c6-de7c4157b02d
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Town
		dataType: string
		lineageTag: c9b6a81e-f48f-4ec4-acfd-1d57c051070d
		summarizeBy: none
		sourceColumn: Town

		annotation SummarizationSetBy = Automatic

	column Wikipedia
		dataType: string
		lineageTag: 77e1b9dc-d483-4c60-b1ae-917fb2dc6742
		summarizeBy: none
		sourceColumn: Wikipedia

		annotation SummarizationSetBy = Automatic

	partition Geography = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\betin\Desktop\case_1\dados-20260401T170821Z-1-001\dados\Dimensions\Geography.xlsx"), null, true),
				    Geography_Sheet = Fonte{[Item="Geography",Kind="Sheet"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(Geography_Sheet,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}}),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Tipo Alterado", [PromoteAllScalars=true]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Country", type text}, {"Town", type text}, {"Wikipedia", type text}})
				in
				    #"Tipo Alterado1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

